### ISSUE TITLE
The firmware update doesn't seem to be working...

### ISSUE THREAD

**Issue by oirad80** [GeekMagicClock/smalltvpro#12]
First of all, congratulations for this project! When I try to update the firmware on my SmallTV Pro and click on "update", I get the following error: "Update error: Wrong Magic Byte". I've tried different firmware, without success my Small TV Pro has firmware V3.2.16EN. I've tried with Chrome, Edge. brave... in private mode without success... any ideas?

**Comment by GeekMagicClock** [comment]
Hello, that error means that's possiblely wrong firmware file for smalltv pro.
1. Make sure the correct firmware file is uploaded.
2. Power it off and keep cool for 5 minutes, and reupload it again, this works for some devices.

**Comment by oirad80** [comment]
Thanks for the tip, after leaving my Small TV Pro switched off all day, I tried the firmware update again and it worked on the first try!
