### ISSUE TITLE
Wrong weather encoding

### ISSUE THREAD

**Issue by bendadaniel** [GeekMagicClock/smalltvpro#13]
Hello, weather's city name encoding doesn't work. 

City: Hradec Králové
Language: Czech 
City ID: 3074967

![IMG_0516 Large](https://github.com/GeekMagicClock/smalltvpro/assets/15817021/53106f7f-6dc7-4963-b7a9-aeb94661cf1f)

**Comment by BTC-21** [comment]
It is already mentioned here - https://github.com/GeekMagicClock/smalltvpro/issues/4

**Comment by GeekMagicClock** [comment]
Yeah, this will be fixed soon.

**Comment by GeekMagicClock** [comment]
@bendadaniel Hi, please update to V3.2.21.

**Comment by bendadaniel** [comment]
Solved.
