### ISSUE TITLE
Stock price tracker colors red and green are reversed

### ISSUE THREAD

**Issue by johnmynatt** [GeekMagicClock/smalltvpro#2]
@GeekMagicClock Hello! On **Stock Price Tracker**, the **red and green colors are reversed**.  When the stock price goes UP, the bars and text should show green.  But right now it shows red instead.  Thank you! Great item. I bought two already and will get more.
![reversed-colors](https://github.com/GeekMagicClock/smalltvpro/assets/84406186/65007110-b5e8-4e8d-8579-97dfb39b983a)

**Comment by GeekMagicClock** [comment]
Thank you for the feedback, I may make a mistake, in China, when stock price goes UP, the price is red. Which country are you in?

**Comment by johnmynatt** [comment]
Oh, in USA up is green. The Bitcoin graph on SmallTVPro already shows up as green too.  Perhaps could it be a user setting? 🙂

**Comment by GeekMagicClock** [comment]
OK, i'll fix this in next release, thank you!

**Comment by GeekMagicClock** [comment]
Hi, please check the new V3.2.16 version, thank you!

**Comment by johnmynatt** [comment]
> Hi, please check the new V3.2.16 version, thank you!
Works great -- thank you! 😀 May I add a future wish for this app? It would be great to have settings for other time scales besides 1 minute per bar (30 minutes).  Stock movements during such a short time are usually not meaningful. Possible times like 1 hour per bar (30 hours), 1 day per bar (30 days), and 1 week per bar (30 weeks) available in Settings would make the Stocks app function for a wider range of uses in the same amount of bars.

**Comment by GeekMagicClock** [comment]
OK, let me do some research.

**Comment by pasletner** [comment]
Great little screen, and I immediately ordered one more. Would it be possible to increase the number of stocks monitored? Lets say 8 or 10?

**Comment by GeekMagicClock** [comment]
Yeah, that's possible, let me test it.

**Comment by GeekMagicClock** [comment]
Hi, @pasletner please try the V3.2.18EN, 10 stocks and 10 coins are supported, welcome feedback.
