### ISSUE TITLE
Bug with cryptocurrency charts

### ISSUE THREAD

**Issue by Egurt666** [GeekMagicClock/smalltvpro#20]
Hi. After upgrading to firmware version 3.2.23EN, cryptocurrency charts are no longer displayed. 
Please fix it in the next version. I'm rolling back to the previous version for now

**Comment by GeekMagicClock** [comment]
OK, thanks for report, will fix it in next release.

**Comment by GeekMagicClock** [comment]
Hello, any one can help with this? I have create a new coin UI, but due to the limit of my network, I can't do enough test, I'll send the firmware via email.

**Comment by GeekMagicClock** [comment]
Thanks for the help of @davisdmg , the V3.2.24EN is released, please update and add your feedback.

**Comment by davisdmg** [comment]
Thanks for your work!

**Comment by Egurt666** [comment]
Thanks for your work. 
I'm not a designer, but I noticed a couple bugs in the new interface. 
1. too big indentation on the left side of the chart and no indentation on the right side. 
2. The bottom border of the chart frame does not fit into the screen.
I attach a photo 
![photo_2023-12-14_16-56-41](https://github.com/GeekMagicClock/smalltvpro/assets/107801241/4f06f9bf-30f4-4931-a85f-26990ec180af)

**Comment by GeekMagicClock** [comment]
[firmware.zip](https://github.com/GeekMagicClock/smalltvpro/files/13673833/firmware.zip)
please unzip it, and update the firmware.bin file, the UI is adjusted.

**Comment by davisdmg** [comment]
works like a charm ;)

**Comment by Egurt666** [comment]
> [firmware.zip](https://github.com/GeekMagicClock/smalltvpro/files/13673833/firmware.zip) please unzip it, and update the firmware.bin file, the UI is adjusted.

THX . Great work!
