### ISSUE TITLE
Adding Options Contracts Blocks The Loop Of Stocks

### ISSUE THREAD

**Issue by dvsrk** [GeekMagicClock/smalltvpro#22]
For example added this contract [PYPL250117C00062500](https://finance.yahoo.com/quote/PYPL250117C00062500?p=PYPL250117C00062500) and the loop of stocks stopped working after the last stock it hits.

And, it is not the case always though, it works sometimes but not always, it is little flappy. Please check.

btw, I'm using 1d k-line interval.

**Comment by GeekMagicClock** [comment]
Hi, I have tested it on my device, but not happen, can you try the latest V3.2.25?

**Comment by dvsrk** [comment]
I have updated but no luck, I have tried on my 3 devices and the result is same.

**Reproducible Steps:**

1. Reset the device
2. Add following stocks to stocks section, 
    - In my case added following.
        DIS
        NVDA        
3. Enable the loop.
4. Switch back to apps navigation on device and select Stock app.
5. At this stage everything should work as expected.
6. Now add PYPL250117C00080000 as third stock.
7. Reboot the device.
8. Now you will see the loop will stop at NVDA, without moving to 3rd one .

**Comment by GeekMagicClock** [comment]
> I have updated to latest V3.2.25 but no luck, And tried on my all 3 devices and it is same.
> 
> **Reproducible Steps:**
> 
> 1. Reset the device
> 2. Add following stocks to stocks section,
>    
>    * In my case added following.
>      DIS
>      NVDA
> 3. Enable the loop.
> 4. Switch back to apps navigation on device and select Stock app.
> 5. At this stage everything should work as expected.
> 6. Now add PYPL250117C00080000 as third stock.
> 7. Reboot the device.
> 8. Now you will see the loop will stop at NVDA, without moving to 3rd one .

Got it, I'm able to reproduce it, I'll check it out, thank you for the details.

**Comment by GeekMagicClock** [comment]
Hi, it is issue about saving long stock symbol, fixed in the attachement V3.2.25.1, please try, thank you.
[firmware.zip](https://github.com/GeekMagicClock/smalltvpro/files/13695044/firmware.zip)

**Comment by dvsrk** [comment]
It is resolved under attached firmware. Hope it will be undled with your future release.
And just a suggestion or feature request, great if you could make the chart animation introduced in V3.2.25 as an option, so we could enable it only if we need it.
