### ISSUE TITLE
Stock and Bitcoin animation to be optional

### ISSUE THREAD

**Issue by Scabattoir** [GeekMagicClock/smalltvpro#23]
Hi,

I think the Stock and Bitcoin animations make the device less useful.
Any chance that you can make that an option by a check switch in the settings?

Thanks

**Comment by GeekMagicClock** [comment]
https://github.com/GeekMagicClock/smalltvpro/issues/24#issuecomment-1860196612  Please check this.

**Comment by Scabattoir** [comment]
Amazing!
Thank you!
