### ISSUE TITLE
Differences between the three models?

### ISSUE THREAD

**Issue by mbourgon** [GeekMagicClock/smalltvpro#26]
Howdy! Trying to figure out why to buy one model over the other. Regular has no button, unsure of differences between ultra and pro. Thank you! (Sorry to ask here, cannot find other ways)

**Comment by GeekMagicClock** [comment]
Thank you, there should be an image to show the difference, in short here:
**Smalltv**:  only one screen with weather today and time date.
**Smalltv-ultra**: software update version of smalltv, with multi-themes, full screen jpg/gif display, weather forecast, big time theme etc.
**Smalltv-pro**: hardware and software upgrade, with multi-functions, fullscreen jpg/gif display, bitcoin/stock inside, touch button on top, and in active developing.

**Comment by mbourgon** [comment]
Thank you!
