### ISSUE TITLE
Idea app has no available settings

### ISSUE THREAD

**Issue by johnmynatt** [GeekMagicClock/smalltvpro#3]
Hello! I am not sure what the Idea app is. It seems to show animated GIFs for creativity or relaxation.  The Picture app allows changing or removing photos -- will there be settings for changing images in the Idea app also?  Does this share the same storage space?

**Comment by GeekMagicClock** [comment]
Hi, the Idea app is for fun, and maybe removed in future version because of limited rom, it's effect is writen by code, does not take much storage of picture.
