### ISSUE TITLE
Weather app does not support special accent characters in city name

### ISSUE THREAD

**Issue by johnmynatt** [GeekMagicClock/smalltvpro#4]
The name of the city retrieved in the Weather app does not seem to support special accent characters (diacritics).  For example, in São Paulo, Brazil ([https://openweathermap.org/city/3448439](https://openweathermap.org/city/3448439)) the "ã" displays as an empty rectangle on the SmallTVPro. This is a minor issue but I hope it's helpful for those living in such cities.

**Comment by GeekMagicClock** [comment]
Got it, will fix it, thank you!

**Comment by GeekMagicClock** [comment]
Fixed, please update to V3.2.21.
