### ISSUE TITLE
Time syncs wrong time and day on first boot sync

### ISSUE THREAD

**Issue by johnmynatt** [GeekMagicClock/smalltvpro#6]
I've noticed three times when the SmallTVPro first boots and scans for wifi using my phone hotspot, it shows "Connect success... Sync time".  But after booting, in the Weather and Clock apps, the time is exactly 1 day and 2 hours ahead.  For example, my local time is Friday at 4:52pm, but the clock after sync shows Saturday at 6:52pm (I have 12 hour time set).

It is strange because without any wifi/sync on startup, it just shows 12:00 as the time.  In this case the minutes are correct, only the hours are wrong.  So it does seem to be syncing the time on boot except perhaps the correct time zone isn't getting applied.

When I continue using the device entering and exiting other apps, it seems to eventually sync to the right time.  Besides the first sync, does the time sync in other apps like Weather or Stocks, or does the device run a time sync again later?  This wrong time only happens on the first boot.

**Comment by satelliteseeker** [comment]
I'm having the same issue, the hour value was wrong for the first few minutes after boot.

It appears to be a timezone mismatch. Can I force the clock to one timezone in the web config, or use current location from weather API to determine timezone?

**Comment by Popastefanx** [comment]
Same issue here with london timezone

**Comment by GeekMagicClock** [comment]
Thank you for all the feedback, i'll look into this. By default timezone is automatically updated from weather api.

**Comment by GeekMagicClock** [comment]
@satelliteseeker @johnmynatt @Popastefanx  Hi, there's a mistake in the time zone save and read, please try the V3.2.18EN, welcome feedback, thank you all.
