### ISSUE TITLE
Bitcoin candlestick chart time frame change

### ISSUE THREAD

**Issue by BTC-21** [GeekMagicClock/smalltvpro#7]
![btc1](https://github.com/GeekMagicClock/smalltvpro/assets/146104873/2f7011b6-2d31-4889-82c0-41670a0e786b)
Is there any way to change a time frame of candlestick chart from 1 minute to for example 4 hour? 
It would be nice to have an option to set other time frames

**Comment by GeekMagicClock** [comment]
OK, recently will update some parts of the stocks and coins.

**Comment by GeekMagicClock** [comment]
@BTC-21  Please try V3.2.18EN, welcome feedback.

**Comment by johnmynatt** [comment]
> @BTC-21 Please try V3.2.18EN, welcome feedback.

Thanks for the new time periods and more tickers! I updated and see the new options in the web interface, but trying to save new stock ticker symbols shows "**Save Failed**" red error message at the top.  I restarted device and reconnected but same results.

**Comment by BTC-21** [comment]
> @BTC-21 Please try V3.2.18EN, welcome feedback.

Thanks for the reply and fast firmware update! It is working very well, but I see a small issue with a symbol location. It is covering candles, maybe you could replace it to another place - top-left corner of K-Line or have an option to disable it completelly?

![01](https://github.com/GeekMagicClock/smalltvpro/assets/146104873/9255b908-4869-4fdb-81e8-bb8e2258e9ed)
![02](https://github.com/GeekMagicClock/smalltvpro/assets/146104873/22b5cc47-d6ae-4c27-96ea-b9e62594d8e1)

Regarding to @johnmynatt I am able to add a new coin ticker/symbol and it is working good. Looks like it's an issue in stock section

**Comment by GeekMagicClock** [comment]
> > @BTC-21 Please try V3.2.18EN, welcome feedback.
> 
> Thanks for the new time periods and more tickers! I updated and see the new options in the web interface, but trying to save new stock ticker symbols shows "**Save Failed**" red error message at the top. I restarted device and reconnected but same results.

What is the symbol you set?

**Comment by GeekMagicClock** [comment]
> > > @BTC-21 Please try V3.2.18EN, welcome feedback.
> > 
> > 
> > Thanks for the new time periods and more tickers! I updated and see the new options in the web interface, but trying to save new stock ticker symbols shows "**Save Failed**" red error message at the top. I restarted device and reconnected but same results.
> 
> What is the symbol you set?

Sorry it's my fault, quick fixed in V3.2.20.

**Comment by johnmynatt** [comment]
> @BTC-21 Sorry it's my fault, quick fixed in V3.2.20.
Working great now. It's really useful having the other time frames and more symbols. I have two devices already so I can set them on different time frames and monitor short term and long term patterns.  Thanks for the updates! 😀

**Comment by BTC-21** [comment]
> top-left may still becovered by candles, how about on top layer of the candles? this will cover some part of candles.

@GeekMagicClock where exactly on top layer of the candles? I think even top-left corner of the candles (yes, it will stil cover candles) would be better than current position. Is it hard to do an option to completely disable that symbol?

**Comment by GeekMagicClock** [comment]
> > top-left may still becovered by candles, how about on top layer of the candles? this will cover some part of candles.
> 
> @GeekMagicClock where exactly on top layer of the candles? I think even top-left corner of the candles (yes, it will stil cover candles) would be better than current position. Is it hard to do an option to completely disable that symbol?

OK, top-left and an option to enable or disable the interval symbol, it's not hard but need some time, thank you!

**Comment by Yelles** [comment]
could you add 15m timeframe please ? :)

**Comment by GeekMagicClock** [comment]
> could you add 15m timeframe please ? :)

Hi, I'll check if there's such option, if there is, I'll add it.

**Comment by bendadaniel** [comment]
Yea, add 15m timeframe please.

**Comment by GeekMagicClock** [comment]
Hi, 15m is available, will add it to next version.

**Comment by GeekMagicClock** [comment]
15m added, please update to V3.2.21.
